[package]
name = "svm-rs"
version = "0.1.0"
authors = ["ekimglz <mike.glz.96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
